services:
  rsscode:
    image: hanoseok/rsscode:latest
    container_name: rsscode
    restart: unless-stopped
    ports:
      - "32770:3000"
    volumes:
      - rsscode_data:/data

volumes:
  rsscode_data:
